// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	button: {
		/**
		 * S​i​g​n​ ​u​p
		 */
		signUp: string
		/**
		 * S​i​g​n​ ​i​n
		 */
		signIn: string
		/**
		 * U​p​l​o​a​d
		 */
		upload: string
		/**
		 * U​p​l​o​a​d​ ​a​ ​p​i​c​t​u​r​e
		 */
		uploadPicture: string
		/**
		 * N​e​w​ ​e​v​e​n​t
		 */
		newEvent: string
		/**
		 * V​a​l​i​d​a​t​e
		 */
		validate: string
		/**
		 * R​e​f​u​s​e
		 */
		refuse: string
		/**
		 * C​a​p​t​u​r​e
		 */
		captureImage: string
	}
	form: {
		/**
		 * F​i​r​s​t​n​a​m​e
		 */
		firstName: string
		/**
		 * L​a​s​t​n​a​m​e
		 */
		lastName: string
		/**
		 * G​e​n​r​e
		 */
		gender: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		password: string
		/**
		 * C​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d
		 */
		confirmPassword: string
		/**
		 * B​i​r​t​h​d​a​t​e
		 */
		birthdate: string
		/**
		 * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d
		 */
		forgotPassword: string
		/**
		 * S​e​a​r​c​h
		 */
		search: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
		/**
		 * N​a​m​e
		 */
		name: string
		/**
		 * C​u​r​r​e​n​t​ ​p​a​s​s​w​o​r​d
		 */
		currentPassword: string
		/**
		 * N​e​w​ ​p​a​s​s​w​o​r​d
		 */
		newPassword: string
		/**
		 * E​v​e​n​t​ ​t​i​t​l​e
		 */
		eventTitle: string
		/**
		 * A​l​l​ ​d​a​y
		 */
		allDay: string
		/**
		 * S​t​a​r​t​ ​o​f​ ​t​h​e​ ​e​v​e​n​t
		 */
		startEvent: string
		/**
		 * E​n​d​ ​o​f​ ​t​h​e​ ​e​v​e​n​t
		 */
		endEvent: string
	}
	serverError: {
		/**
		 * T​h​e​ ​u​s​e​r​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t
		 */
		userAlreadyExist: string
		/**
		 * T​h​e​ ​u​s​e​r​ ​i​s​ ​a​l​r​e​a​d​y​ ​a​c​t​i​v​a​t​e​d
		 */
		userAlreadyActivated: string
		/**
		 * T​h​e​ ​u​s​e​r​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t
		 */
		userNoExist: string
		/**
		 * T​h​e​ ​u​s​e​r​ ​i​s​ ​n​o​t​ ​a​c​t​i​v​a​t​e​d
		 */
		userNoActivated: string
		/**
		 * U​n​k​n​o​w​n​ ​e​r​r​o​r
		 */
		notKnow: string
		/**
		 * A​n​ ​e​r​r​o​r​ ​h​a​s​ ​o​c​c​u​r​r​e​d
		 */
		errorGlobal: string
		/**
		 * T​h​e​ ​e​m​a​i​l​ ​o​r​ ​p​a​s​s​w​o​r​d​ ​i​s​ ​i​n​c​o​r​r​e​c​t
		 */
		badCredentials: string
		/**
		 * Y​o​u​ ​a​r​e​ ​n​o​t​ ​a​u​t​h​o​r​i​z​e​d​ ​t​o​ ​a​c​c​e​s​s​ ​t​h​i​s​ ​p​a​g​e
		 */
		unauthorized: string
		/**
		 * T​h​e​ ​e​m​a​i​l​ ​i​s​ ​o​u​t​d​a​t​e​d
		 */
		emailOutdated: string
	}
	desc: {
		/**
		 * W​e​l​c​o​m​e​ ​t​o​ ​C​i​r​c​l​e​s​ ​!
		 */
		welcomeExplainTitle: string
		/**
		 * H​e​l​l​o​ ​a​n​d​ ​w​e​l​c​o​m​e​ ​t​o​ ​C​i​r​c​l​e​s​.​ ​D​i​s​c​o​v​e​r​ ​a​m​a​z​i​n​g​ ​C​i​r​c​l​e​s​,​ ​c​o​n​n​e​c​t​ ​w​i​t​h​ ​p​e​o​p​l​e​ ​w​o​r​l​d​w​i​d​e​,​ ​a​n​d​ ​s​h​a​r​e​ ​y​o​u​r​ ​p​a​s​s​i​o​n​s​.
		 */
		welcomeExplain1: string
		/**
		 * J​o​i​n​ ​l​i​k​e​-​m​i​n​d​e​d​ ​i​n​d​i​v​i​d​u​a​l​s​,​ ​e​n​g​a​g​e​ ​i​n​ ​m​e​a​n​i​n​g​f​u​l​ ​d​i​s​c​u​s​s​i​o​n​s​,​ ​a​n​d​ ​e​x​c​h​a​n​g​e​ ​i​d​e​a​s​ ​i​n​ ​C​i​r​c​l​e​s​ ​t​a​i​l​o​r​e​d​ ​t​o​ ​y​o​u​r​ ​i​n​t​e​r​e​s​t​s​.
		 */
		welcomeExplain2: string
		/**
		 * P​r​o​f​i​l​e​ ​p​i​c​t​u​r​e
		 */
		welcomeProfileTitle: string
		/**
		 * T​h​e​n​ ​y​o​u​ ​c​a​n​ ​c​h​o​o​s​e​ ​t​o​ ​t​a​k​e​ ​a​ ​p​h​o​t​o​ ​o​f​ ​y​o​u​r​s​e​l​f​,​ ​u​p​l​o​a​d​ ​a​ ​p​h​o​t​o​,​ ​o​r​ ​s​k​i​p​ ​t​h​i​s​ ​s​t​e​p​ ​a​n​d​ ​g​e​t​ ​a​ ​c​o​m​m​o​n​ ​a​v​a​t​a​r​.​ ​T​h​i​s​ ​w​i​l​l​ ​a​l​l​o​w​ ​o​t​h​e​r​ ​u​s​e​r​s​ ​t​o​ ​g​e​t​ ​t​o​ ​k​n​o​w​ ​y​o​u​ ​b​e​t​t​e​r​.
		 */
		welcomeProfileExplain: string
		/**
		 * T​a​k​e​ ​a​ ​p​i​c​t​u​r​e
		 */
		takePicture: string
		/**
		 * U​p​l​o​a​d​ ​a​ ​p​i​c​t​u​r​e
		 */
		uploadPicture: string
		/**
		 * E​m​a​i​l​ ​s​e​n​d
		 */
		emailSend: string
		/**
		 * C​l​i​c​k​ ​o​n​ ​t​h​e​ ​l​i​n​k​ ​i​n​t​o​ ​t​h​e​ ​e​m​a​i​l​ ​y​o​u​ ​r​e​c​e​i​v​e​ ​t​o​ ​b​e​g​i​n​ ​y​o​u​r​ ​j​o​u​r​n​e​y​ ​!
		 */
		emailLink: string
		/**
		 * T​h​e​ ​l​i​n​k​ ​i​s​ ​n​o​ ​l​o​n​g​e​r​ ​v​a​l​i​d
		 */
		emailLinkNoValid: string
		/**
		 * P​l​e​a​s​e​ ​r​e​c​o​n​n​e​c​t​ ​y​o​u​ ​t​o​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​a​n​d​ ​r​e​-​s​e​n​d​ ​a​n​ ​a​c​t​i​v​a​t​i​o​n​ ​e​m​a​i​l​.
		 */
		emailAskResend: string
		/**
		 * Y​o​u​r​ ​a​c​c​o​u​n​t​ ​h​a​s​ ​b​e​e​n​ ​v​a​l​i​d​a​t​e​d​ ​!
		 */
		accountValidate: string
		/**
		 * Y​o​u​ ​c​a​n​ ​n​o​w​ ​s​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​t​o​ ​e​n​j​o​y​ ​C​i​r​c​l​e​s​.
		 */
		accountAskSignin: string
		/**
		 * Y​o​u​r​ ​a​c​c​o​u​n​t​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​f​i​n​a​l​i​z​e​d​.​ ​S​t​a​r​t​ ​y​o​u​r​ ​C​i​r​c​l​e​s​ ​e​x​p​e​r​i​e​n​c​e​ ​b​y​ ​p​r​e​s​s​i​n​g​ ​t​h​e​ ​b​u​t​t​o​n​ ​b​e​l​o​w​.
		 */
		welcomeDoneDesc: string
		/**
		 * I​t​ ​s​e​e​m​s​ ​t​h​a​t​ ​y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​n​y​ ​C​i​r​c​l​e​s​.
		 */
		noCircle: string
		/**
		 * Y​o​u​ ​c​a​n​ ​e​i​t​h​e​r​ ​c​r​e​a​t​e​ ​a​ ​n​e​w​ ​C​i​r​c​l​e​ ​o​r​ ​w​a​i​t​ ​t​o​ ​b​e​ ​i​n​v​i​t​e​d​ ​i​n​t​o​ ​o​n​e​.
		 */
		noCircleDesc: string
		/**
		 * F​a​v​o​r​i​t​e​ ​C​i​r​c​l​e​s
		 */
		favCircle: string
		/**
		 * Y​o​u​r​ ​C​i​r​c​l​e​s​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​c​r​e​a​t​e​d
		 */
		createdCircle: string
		/**
		 * Y​o​u​r​ ​e​v​e​n​t​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​c​r​e​a​t​e​d
		 */
		createEvent: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * G​l​o​b​a​l
		 */
		global: string
		/**
		 * P​r​o​f​i​l​e
		 */
		profile: string
		/**
		 * N​o​ ​c​h​a​n​g​e​s​ ​m​a​d​e​.
		 */
		noChange: string
		/**
		 * Y​o​u​r​ ​p​r​o​f​i​l​e​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​u​p​d​a​t​e​d​.
		 */
		updateUserSuccess: string
		/**
		 * T​h​e​ ​n​e​w​ ​p​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​d​i​f​f​e​r​e​n​t​ ​f​r​o​m​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​o​n​e​.
		 */
		passwordSameError: string
		/**
		 * T​h​e​ ​c​u​r​r​e​n​t​ ​p​a​s​s​w​o​r​d​ ​i​s​ ​i​n​v​a​l​i​d​.
		 */
		invalidCurrentPassword: string
		/**
		 * T​h​e​ ​c​u​r​r​e​n​t​ ​p​a​s​s​w​o​r​d​ ​i​s​ ​r​e​q​u​i​r​e​d​.
		 */
		currentpasswordRequired: string
		/**
		 * T​h​e​ ​c​o​n​f​i​r​m​a​t​i​o​n​ ​o​f​ ​t​h​e​ ​n​e​w​ ​p​a​s​s​w​o​r​d​ ​i​s​ ​r​e​q​u​i​r​e​d​.
		 */
		confirmpasswordRequired: string
		/**
		 * T​h​e​ ​n​e​w​ ​p​a​s​s​w​o​r​d​ ​i​s​ ​r​e​q​u​i​r​e​d​.
		 */
		newpasswordRequired: string
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​e​v​e​n​t​?
		 */
		deleteEvent: string
		/**
		 * Y​o​u​r​ ​e​v​e​n​t​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​m​o​d​i​f​i​e​d​.
		 */
		modifyEventSuccess: string
		/**
		 * Y​o​u​r​ ​e​v​e​n​t​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​d​e​l​e​t​e​d​.
		 */
		deleteEventSuccess: string
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​v​a​l​i​d​a​t​e​ ​t​h​i​s​ ​i​m​a​g​e​?
		 */
		askImage: string
		/**
		 * Y​o​u​r​ ​p​r​o​f​i​l​e​ ​p​i​c​t​u​r​e​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​u​p​d​a​t​e​d​.
		 */
		imgProfileSuccess: string
		/**
		 * A​n​ ​e​r​r​o​r​ ​h​a​s​ ​o​c​c​u​r​r​e​d​ ​w​h​i​l​e​ ​u​p​d​a​t​i​n​g​ ​y​o​u​r​ ​p​r​o​f​i​l​e​ ​p​i​c​t​u​r​e​.
		 */
		imgProfileError: string
	}
	global: {
		/**
		 * f​r
		 */
		switchLanguage: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		language: string
		/**
		 * F​r​a​n​ç​a​i​s
		 */
		fr: string
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
		/**
		 * F​e​r​m​e​r
		 */
		close: string
		/**
		 * O​r
		 */
		or: string
		/**
		 * N​e​x​t
		 */
		next: string
		/**
		 * S​k​i​p
		 */
		skip: string
		/**
		 * S​t​a​r​t
		 */
		start: string
		/**
		 * P​e​r​f​e​c​t​ ​!
		 */
		perfect: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * C​o​n​f​i​r​m
		 */
		confirm: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * M​o​d​i​f​y
		 */
		modify: string
	}
}

export type TranslationFunctions = {
	button: {
		/**
		 * Sign up
		 */
		signUp: () => LocalizedString
		/**
		 * Sign in
		 */
		signIn: () => LocalizedString
		/**
		 * Upload
		 */
		upload: () => LocalizedString
		/**
		 * Upload a picture
		 */
		uploadPicture: () => LocalizedString
		/**
		 * New event
		 */
		newEvent: () => LocalizedString
		/**
		 * Validate
		 */
		validate: () => LocalizedString
		/**
		 * Refuse
		 */
		refuse: () => LocalizedString
		/**
		 * Capture
		 */
		captureImage: () => LocalizedString
	}
	form: {
		/**
		 * Firstname
		 */
		firstName: () => LocalizedString
		/**
		 * Lastname
		 */
		lastName: () => LocalizedString
		/**
		 * Genre
		 */
		gender: () => LocalizedString
		/**
		 * Password
		 */
		password: () => LocalizedString
		/**
		 * Confirm password
		 */
		confirmPassword: () => LocalizedString
		/**
		 * Birthdate
		 */
		birthdate: () => LocalizedString
		/**
		 * Forgot password
		 */
		forgotPassword: () => LocalizedString
		/**
		 * Search
		 */
		search: () => LocalizedString
		/**
		 * Description
		 */
		description: () => LocalizedString
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * Current password
		 */
		currentPassword: () => LocalizedString
		/**
		 * New password
		 */
		newPassword: () => LocalizedString
		/**
		 * Event title
		 */
		eventTitle: () => LocalizedString
		/**
		 * All day
		 */
		allDay: () => LocalizedString
		/**
		 * Start of the event
		 */
		startEvent: () => LocalizedString
		/**
		 * End of the event
		 */
		endEvent: () => LocalizedString
	}
	serverError: {
		/**
		 * The user already exist
		 */
		userAlreadyExist: () => LocalizedString
		/**
		 * The user is already activated
		 */
		userAlreadyActivated: () => LocalizedString
		/**
		 * The user does not exist
		 */
		userNoExist: () => LocalizedString
		/**
		 * The user is not activated
		 */
		userNoActivated: () => LocalizedString
		/**
		 * Unknown error
		 */
		notKnow: () => LocalizedString
		/**
		 * An error has occurred
		 */
		errorGlobal: () => LocalizedString
		/**
		 * The email or password is incorrect
		 */
		badCredentials: () => LocalizedString
		/**
		 * You are not authorized to access this page
		 */
		unauthorized: () => LocalizedString
		/**
		 * The email is outdated
		 */
		emailOutdated: () => LocalizedString
	}
	desc: {
		/**
		 * Welcome to Circles !
		 */
		welcomeExplainTitle: () => LocalizedString
		/**
		 * Hello and welcome to Circles. Discover amazing Circles, connect with people worldwide, and share your passions.
		 */
		welcomeExplain1: () => LocalizedString
		/**
		 * Join like-minded individuals, engage in meaningful discussions, and exchange ideas in Circles tailored to your interests.
		 */
		welcomeExplain2: () => LocalizedString
		/**
		 * Profile picture
		 */
		welcomeProfileTitle: () => LocalizedString
		/**
		 * Then you can choose to take a photo of yourself, upload a photo, or skip this step and get a common avatar. This will allow other users to get to know you better.
		 */
		welcomeProfileExplain: () => LocalizedString
		/**
		 * Take a picture
		 */
		takePicture: () => LocalizedString
		/**
		 * Upload a picture
		 */
		uploadPicture: () => LocalizedString
		/**
		 * Email send
		 */
		emailSend: () => LocalizedString
		/**
		 * Click on the link into the email you receive to begin your journey !
		 */
		emailLink: () => LocalizedString
		/**
		 * The link is no longer valid
		 */
		emailLinkNoValid: () => LocalizedString
		/**
		 * Please reconnect you to your account and re-send an activation email.
		 */
		emailAskResend: () => LocalizedString
		/**
		 * Your account has been validated !
		 */
		accountValidate: () => LocalizedString
		/**
		 * You can now sign in to your account to enjoy Circles.
		 */
		accountAskSignin: () => LocalizedString
		/**
		 * Your account has been successfully finalized. Start your Circles experience by pressing the button below.
		 */
		welcomeDoneDesc: () => LocalizedString
		/**
		 * It seems that you don't have any Circles.
		 */
		noCircle: () => LocalizedString
		/**
		 * You can either create a new Circle or wait to be invited into one.
		 */
		noCircleDesc: () => LocalizedString
		/**
		 * Favorite Circles
		 */
		favCircle: () => LocalizedString
		/**
		 * Your Circles has been successfully created
		 */
		createdCircle: () => LocalizedString
		/**
		 * Your event has been successfully created
		 */
		createEvent: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Global
		 */
		global: () => LocalizedString
		/**
		 * Profile
		 */
		profile: () => LocalizedString
		/**
		 * No changes made.
		 */
		noChange: () => LocalizedString
		/**
		 * Your profile has been successfully updated.
		 */
		updateUserSuccess: () => LocalizedString
		/**
		 * The new password must be different from the current one.
		 */
		passwordSameError: () => LocalizedString
		/**
		 * The current password is invalid.
		 */
		invalidCurrentPassword: () => LocalizedString
		/**
		 * The current password is required.
		 */
		currentpasswordRequired: () => LocalizedString
		/**
		 * The confirmation of the new password is required.
		 */
		confirmpasswordRequired: () => LocalizedString
		/**
		 * The new password is required.
		 */
		newpasswordRequired: () => LocalizedString
		/**
		 * Are you sure you want to delete this event?
		 */
		deleteEvent: () => LocalizedString
		/**
		 * Your event has been successfully modified.
		 */
		modifyEventSuccess: () => LocalizedString
		/**
		 * Your event has been successfully deleted.
		 */
		deleteEventSuccess: () => LocalizedString
		/**
		 * Are you sure you validate this image?
		 */
		askImage: () => LocalizedString
		/**
		 * Your profile picture has been successfully updated.
		 */
		imgProfileSuccess: () => LocalizedString
		/**
		 * An error has occurred while updating your profile picture.
		 */
		imgProfileError: () => LocalizedString
	}
	global: {
		/**
		 * fr
		 */
		switchLanguage: () => LocalizedString
		/**
		 * Language
		 */
		language: () => LocalizedString
		/**
		 * Français
		 */
		fr: () => LocalizedString
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * Fermer
		 */
		close: () => LocalizedString
		/**
		 * Or
		 */
		or: () => LocalizedString
		/**
		 * Next
		 */
		next: () => LocalizedString
		/**
		 * Skip
		 */
		skip: () => LocalizedString
		/**
		 * Start
		 */
		start: () => LocalizedString
		/**
		 * Perfect !
		 */
		perfect: () => LocalizedString
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Confirm
		 */
		confirm: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Modify
		 */
		modify: () => LocalizedString
	}
}

export type Formatters = {}
