version: '4.12'
services:
  dev-db:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  test-db:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env.test
