// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​i​g​n​ ​u​p
	 */
	SIGNUP: string
	/**
	 * f​r
	 */
	SWITCH_LANGUAGE: string
}

export type TranslationFunctions = {
	/**
	 * Sign up
	 */
	SIGNUP: () => LocalizedString
	/**
	 * fr
	 */
	SWITCH_LANGUAGE: () => LocalizedString
}

export type Formatters = {}
